from cryptography.fernet import Fernet
import json

# generate the key and store it
key = Fernet.generate_key()
with open("files/cles/secret_1.key", "wb") as key_file:
    key_file.write(key)

# Encrypt data, place your appId and secretID generated by your API
fernet = Fernet(key)
secrets = {
    "appId": "",  # FILL YOUR OWN APP ID
    "secretId": ""  # FILL YOUR OWN SECRET
}

encrypted = fernet.encrypt(json.dumps(secrets).encode())

# final encrypted file
with open("files/cles/secrets_1.enc", "wb") as f:
    f.write(encrypted)
